### ISSUE TITLE
add_to_queue breaks in python3

### ISSUE THREAD

**Issue by petteraas** [SoCo/SoCo#134]
Try the new `ml_*` commands from `socos` to see the problem, it works perfectly in 2.7, but breaks in 3.3 with:

```
ml_albums % add 18
Traceback (most recent call last):
  File "/home/petter/.virtualenvs/python3.3/bin/socos", line 9, in <module>
    load_entry_point('socos==0.1', 'console_scripts', 'socos')()
  File "/home/petter/.virtualenvs/python3.3/lib/python3.3/site-packages/socos/runner.py", line 22, in main
    shell()
  File "/home/petter/.virtualenvs/python3.3/lib/python3.3/site-packages/socos/core.py", line 165, in shell
    process_cmd(args)
  File "/home/petter/.virtualenvs/python3.3/lib/python3.3/site-packages/socos/core.py", line 75, in process_cmd
    for line in result:
  File "/home/petter/.virtualenvs/python3.3/lib/python3.3/site-packages/socos/music_lib.py", line 158, in albums
    for string in self._search_and_play(sonos, 'albums', *args):
  File "/home/petter/.virtualenvs/python3.3/lib/python3.3/site-packages/socos/music_lib.py", line 221, in _search_and_play
    yield self._play(sonos, data_type, results, *args)
  File "/home/petter/.virtualenvs/python3.3/lib/python3.3/site-packages/socos/music_lib.py", line 304, in _play
    sonos.add_to_queue(item)
  File "/home/petter/.virtualenvs/python3.3/lib/python3.3/site-packages/soco/core.py", line 1150, in add_to_queue
    metadata = metadata.encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'
```

I think the reason is this:

ElementTree.tostring in Python2.7

```
xml.etree.ElementTree.tostring(element, encoding="us-ascii", method="xml")
Generates a string representation of an XML element, including all subelements. element is an Element instance. encoding [1] is the output encoding (default is US-ASCII). method is either "xml", "html" or "text" (default is "xml"). Returns an encoded string containing the XML data.
```

same in Python3

```
xml.etree.ElementTree.tostring(element, encoding="us-ascii", method="xml", *, short_empty_elements=True)
Generates a string representation of an XML element, including all subelements. element is an Element instance. encoding [1] is the output encoding (default is US-ASCII). Use encoding="unicode" to generate a Unicode string (otherwise, a bytestring is generated). method is either "xml", "html" or "text" (default is "xml"). short_empty_elements has the same meaning as in ElementTree.write(). Returns an (optionally) encoded string containing the XML data.
```

You'll notice the default bytestring output in 3.3

https://github.com/SoCo/SoCo/blob/master/soco/core.py#L1143
https://github.com/SoCo/SoCo/blob/master/soco/core.py#L1149
