### ISSUE TITLE
Drop pylint checks for Py2.6?

### ISSUE THREAD

**Issue by lawrenceakka** [SoCo/SoCo#363]
At the moment, we have pinned PyLint at version 1.3.1 and astroid at 1.2.1 as later versions have dropped support for Python 2.6 (see #255). PyLint is now at version 1.4.4 and astroid at 1.3.8.  

There are various problems with this.  The newer versions include important checks for Python 3 which we are missing, and the older versions cannot cope with e.g. the way in which we declare metaclasses (which is forced on us because  we need to be compatible with Py2 and Py3).  For example, running PyLint 1.3.1 against the new docs branch results in:

```
************* Module soco.core
E:  1255,15:  Unexpected keyword argument 'title' in constructor call (unexpected-keyword-arg)
E:  1255,15:  Unexpected keyword argument 'item_id' in constructor call (unexpected-keyword-arg)
E:  1255,15:  Unexpected keyword argument 'resources' in constructor call (unexpected-keyword-arg)
E:  1255,15:  Unexpected keyword argument 'parent_id' in constructor call (unexpected-keyword-arg)
E:  1255,15:  No value for argument 'name' in constructor call (no-value-for-parameter)
E:  1255,15:  No value for argument 'this_bases' in constructor call (no-value-for-parameter)
E:  1255,15:  No value for argument 'd' in constructor call (no-value-for-parameter)
E:  1410,15:  Unexpected keyword argument 'title' in constructor call (unexpected-keyword-arg)
E:  1410,15:  Unexpected keyword argument 'item_id' in constructor call (unexpected-keyword-arg)
E:  1410,15:  Unexpected keyword argument 'resources' in constructor call (unexpected-keyword-arg)
E:  1410,15:  Unexpected keyword argument 'parent_id' in constructor call (unexpected-keyword-arg)
E:  1410,15:  No value for argument 'name' in constructor call (no-value-for-parameter)
E:  1410,15:  No value for argument 'this_bases' in constructor call (no-value-for-parameter)
E:  1410,15:  No value for argument 'd' in constructor call (no-value-for-parameter)
E:  1435,15:  Unexpected keyword argument 'title' in constructor call (unexpected-keyword-arg)
E:  1435,15:  Unexpected keyword argument 'item_id' in constructor call (unexpected-keyword-arg)
E:  1435,15:  Unexpected keyword argument 'resources' in constructor call (unexpected-keyword-arg)
E:  1435,15:  Unexpected keyword argument 'parent_id' in constructor call (unexpected-keyword-arg)
E:  1435,15:  No value for argument 'name' in constructor call (no-value-for-parameter)
E:  1435,15:  No value for argument 'this_bases' in constructor call (no-value-for-parameter)
E:  1435,15:  No value for argument 'd' in constructor call (no-value-for-parameter)

etc

```

Newer pylint (rightly) has no problems. It seems fairly pointless to fix all of these by `pylint: disable` commands just so we can continue running an out-of-date version of pylint.

I therefore propose that 
* we remove the pinning and use the up-to-date version of pylint. 
* we no longer run pylint in our Travis checks for Python 2.6. (NB py.test will continue to run, so should pick up problems)

@robwebset, @stefankoegl, @KennethNielsen and others, what are your views?

**Comment by stefankoegl** [comment]
Good idea! 

I'm don't know how this can be done in Travis, but I'm sure there will be some way.

**Comment by lawrenceakka** [comment]
Done.  Flake8 is still running on Py2.6  Pylint does not yet work on Py3.5 so that is not enabled

**Comment by KennethNielsen** [comment]
Great! If not in Travis it may also be possible to do with the make file,but I see that you figured it out.
