### ISSUE TITLE
Basic usage issue on Raspberry Pi (Python 2.7.3)

### ISSUE THREAD

**Issue by CashWilliams** [SoCo/SoCo#270]
I've installed pip and run the installation as shown in readme. This is on a raspberry pi, which seem to come with an older version of Python, but I'm hesitant to upgrade Python since I have a lot of other scripts already running and working with the GPIO ports.

Also I know nothing about Python, so please bear with me. Running with sudo since scripts need access to GPIO.

```Shell
pi@raspberrypi ~ $ sudo pip install soco --upgrade
Requirement already up-to-date: soco in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages (from soco)
pi@raspberrypi ~ $ python --version
Python 2.7.3
pi@raspberrypi ~ $ cat soco.py
import soco
for zone in soco.discover():
    print(zone.player_name)
pi@raspberrypi ~ $ sudo python soco.py
Traceback (most recent call last):
  File "soco.py", line 1, in <module>
    import soco
  File "/home/pi/soco.py", line 2, in <module>
    for zone in soco.discover():
AttributeError: 'module' object has no attribute 'discover'
```

**Comment by DPH** [comment]
Hi, the Raspberry Pi has Python 2.7 installed by default. Newer Pi's still have 2.7, but also a version of 3. SoCo works with Python 2,7 and 3.2+. I run SoCo on Raspberry Pi with no problem using python 2.7. So Pi looks OK.

You code works perfectly using the current version of SoCo 0.10 available from https://pypi.python.org/pypi/soco/ in my test (on Windows but never had an issue moving stuff to Pi)

I suspect your version of SoCo is not the latest official release. Suggest you remove and re-install SoCo and test again. I don't understand why --upgrade doesn't work - maybe the experts can comment.

Hope this helps - let us know if this fixes it, do shout again if we can help. 
Cheers David

**Comment by lawrenceakka** [comment]
Closing for now - please feel free to reopen if David's comment doesn't fix this.
